//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################

 #pragma once
  
#include "AEEventBase.h"
  
  
  
 
  
class LoraMsgReceived : public AEEventBase
{
public: 
	static EventPoolSize_t EvtIdStatic;

	int16_t sendingLoraAddress;
int8_t payloadsize;
char payload[200];
 
	 
};