//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################



using CgenMin.MacroProcesses;
using System.Collections.Generic;

namespace lucislidelightProject
{

    public class lucislidelight : AEProject
    {
		[AEEXETest]
        public void defaultTest()
        {

        }

        protected override string _GetDirectoryOfLibrary()
        {
            return @"lucislidelight"; 
        }

        protected override List<AEEvent> _GetEventsInLibrary()
        {
            return new List<AEEvent>() { };
        }

		protected override List<AEHal> _GetPeripheralsInLibrary()
        {
		//ADCPERIPHERAL1_CH1.Init(Portenum.PortB, PinEnum.PIN0)
            return new List<AEHal>() {
                UARTPERIPHERAL2.Init(BaudRatesEnum.T_115200,1,Portenum.PortA, PinEnum.PIN2, Portenum.PortA, PinEnum.PIN3),
                PWMPERIPHERAL1.Init(Portenum.PortD, PinEnum.PIN12)

            };
        }

        protected override List<AEProject> _GetLibrariesIDependOn()
        {
            return new List<AEProject>() { };
        }
		
		protected override List<string> _GetAnyAdditionalIncludeDirs()
        {
            return new List<string>() { };
        }
		
		protected override List<string> _GetAnyAdditionalSRCDirs()
        {
            return new List<string>() {  };
        }
		
 
    }
	
	
	
}