//generated file: C:/AERTOSProjects/lucislidelight\defaultTest.cpp
//**********************************************************************
//this is an auto-generated file using the template file located in the directory of C:\CodeGenerator\CodeGenerator\bin\Debug\..\..\FileTemplates\Files
//ONLY WRITE CODE IN THE UserCode_Section BLOCKS
//If you write code anywhere else,  it will be overwritten. modify the actual template file if needing to modify code outside usersection blocks.

//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################


 
#if INTEGRATION_TESTS_FOR_lucislidelight__defaultTest
 
#include "IntegTestPipeline.h"


#include "AECore.h"
#include "AE_Init.h" 
#include "AEClock.h" 
#include "AEObjects.h" 

DECLARE_ALL_AO_PTR





//UserCode_Sectiona
//UserCode_Sectiona_end

void RunSelectedIntegrationTest_defaultTest()
{

AE_Init();
 //UserCode_Sectionbeforemain
	PWMPERIPHERAL_inst1->StartPWM();
	PWMPERIPHERAL_inst1->ChangeDutyCycle(0);
	
	UARTPERIPHERAL_inst2->SetRxCpltCallback([](char* msgReceived, uint32_t sizeOfReceivedMsg) -> void { 
		int dutycycle = (int)*msgReceived;// - '0';
		PWMPERIPHERAL_inst1->ChangeDutyCycle(dutycycle);
	} );
	
 
	
//UserCode_Sectionbeforemain_end





//UserCode_Sectionbeforelinks
//UserCode_Sectionbeforelinks_end



//UserCode_Sectionbeforeclock
//UserCode_Sectionbeforeclock_end


//AEITEST_END_TestsAfterTimer_lucislidelight(5000);
//UserCode_Sectionb
//UserCode_Sectionb_end

AEAO::ConfigureAndStart();
}


//UserCode_Sectionc
//UserCode_Sectionc_end





#endif