################################################ 
#this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
################################################



#Cgen_Start(CGEN_PROJECT_DIRECTORY "C:/AERTOSProjects/commonAOs")

MATH(EXPR _arg_ONLY_CREATE_LIBRARY "${_arg_ONLY_CREATE_LIBRARY}+1")
include("C:/AERTOSProjects/commonAOs/AEConfigProject.cmake")
MATH(EXPR _arg_ONLY_CREATE_LIBRARY "${_arg_ONLY_CREATE_LIBRARY}-1")

#CREATE_TARGET_INTEGRATIONEXE(NAME_OF_TARGET commonAOs
#LOCATION_OF_TARGET "C:/AERTOSProjects/commonAOs"
#LibrariesToLinkTo AECoreLib 
#ONLY_CREATE_LIBRARY TRUE
#)  
#Cgen_End_Session()
  
#Cgen_Start(CGEN_PROJECT_DIRECTORY "C:/AERTOSProjects/commonHalAOs")

MATH(EXPR _arg_ONLY_CREATE_LIBRARY "${_arg_ONLY_CREATE_LIBRARY}+1")
include("C:/AERTOSProjects/commonHalAOs/AEConfigProject.cmake")
MATH(EXPR _arg_ONLY_CREATE_LIBRARY "${_arg_ONLY_CREATE_LIBRARY}-1")

#CREATE_TARGET_INTEGRATIONEXE(NAME_OF_TARGET commonHalAOs
#LOCATION_OF_TARGET "C:/AERTOSProjects/commonHalAOs"
#LibrariesToLinkTo AECoreLib 
#ONLY_CREATE_LIBRARY TRUE
#)  
#Cgen_End_Session()
 

if(((${_arg_ONLY_CREATE_LIBRARY} STREQUAL 0 )))
Cgen_Start(CGEN_PROJECT_DIRECTORY "C:/AERTOSProjects/blinky")

 
Cgen_Option(
        NAME INTEGRATION_TESTS
        DESCRIPTION "choose an integration test directory to build"
        POSSIBLEVALUES blinky 
        CONSTRICTS_LATER_OPTIONS
)

else()
 
Cgen_Start(CGEN_PROJECT_DIRECTORY "${CMAKE_CURRENT_LIST_DIR}")

endif()


if(EXISTS "${CMAKE_CURRENT_LIST_DIR}/AEConfigProjectUser.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/AEConfigProjectUser.cmake")
endif()

CREATE_TARGET_INTEGRATIONEXE(NAME_OF_TARGET blinky
LOCATION_OF_TARGET "C:/AERTOSProjects/blinky"
LibrariesToLinkTo AECoreLib commonAOs_lib commonHalAOs_lib
AnyAdditionalIncludeDirs  
AnyAdditionalSRCDirs 
LIST_OF_TESTS defaultTest
) 




if(((${_arg_ONLY_CREATE_LIBRARY} STREQUAL 0 )))
 CGEN_END()
  else()
 Cgen_End_Session()
 endif()
 
 


