//generated file: C:/AERTOSProjects/commonHalAOs\include\MotorDriverU.h
//**********************************************************************
//this is an auto-generated file using the template file located in the directory of C:\CodeGenerator\CodeGenerator\bin\Debug\..\..\FileTemplates\Files
//ONLY WRITE CODE IN THE UserCode_Section BLOCKS
//If you write code anywhere else,  it will be overwritten. modify the actual template file if needing to modify code outside usersection blocks.

//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################


#pragma once

#include "AEUtilityAsService.h" 

#include "AEPublishSubscribeManager.h" 

#include "ActionRequestObjectArgTDU.h"
 
#include "AE_TDUAsService.h" 

#include "MotorDriverU_ServiceGen.h"


#include "GPIOsNeededForMotor.h"


//UserCode_Sectionheader
//UserCode_Sectionheader_end

class MotorDriverU :   
	 public AEService< 10 , ActionRequestObjectArg2<bool , bool , AENull, 10, MotorDriverU>, AENullActionRequest, AENullActionRequest, AENullActionRequest, AENullActionRequest, AENullActionRequest >
{
public: 

	//UserCode_Sectionpublic
//UserCode_Sectionpublic_end
	 
	MotorDriverU ()
	{ 
		ActionReq1.ServiceName = "MotorDriverTurn"; //ActionReq1.ServiceName = "Transmit";
		
		
		
		
		 
		 
		MotorDriverU_CTOR
		
		//UserCode_Sectionctor
//UserCode_Sectionctor_end
		 	
	}
	MotorDriverU_Service
	
	
	protected: GPIOsNeededForMotor* gPIOsNeeded; 
public: GPIOsNeededForMotor*  GetgPIOsNeeded()   const {return gPIOsNeeded; }
public:  void SetgPIOsNeeded(GPIOsNeededForMotor*  _gPIOsNeeded){gPIOsNeeded = _gPIOsNeeded; }


public: void UserInitialize(GPIOsNeededForMotor* _gPIOsNeeded )
	{
		gPIOsNeeded =  _gPIOsNeeded;

		
		//UserCode_SectionuserInited
//UserCode_SectionuserInited_end
		
		userInitialized = true;
	}
private: bool userInitialized = false;
protected: void CheckIfConfiguredProperly() const override  
	{
		//MotorDriverU::CheckIfConfiguredProperly();
		if (userInitialized == false)
		{
			// you did not initialize one of your AEobjects
			AEAssertRuntime(userInitialized == true, "user did not call the UserInitailize function for  MotorDriverU"); 
		} 
		 
	}
	
protected: 
	
	//UserCode_Sectionprot
//UserCode_Sectionprot_end
	
	
	//example for waiting on an event
	//actReq->WaitForEvent<SomeOther_Sig>(
	//				[](void* s, AEEventDiscriminator_t* evt)->void {
	//					//SomeOther_Sig* sssc = (SomeOther_Sig*)evt->evt;
	//					AEPrint("Event SomeOther_Sig recieved"); 
	//					return;
	//				}
	//				, 500);
	
	//dont forget to return the service value when finished
	//actReq->SetReturnArg(1); 
	
	//return true in the update function for tdus when the service is done.
	
	//=====================================
	//Normal services
	//=====================================
	void _MotorDriverTurn(bool TurnOn, bool ClockWise) 
   {

         //UserCode_SectionMotorDriverTurn
//UserCode_SectionMotorDriverTurn_end 
   }
  
	  
	  
	
	
	//=====================================
	//TDU services
	//=====================================
	  
	  
	  
	 
	  

};




//UserCode_Sectionfunc
//UserCode_Sectionfunc_end