//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################


#define MotorDriverU_MotorDriverTurn_CTOR ActionReq1.SetServiceFunc([](MotorDriverU* p, bool TurnOn, bool ClockWise){p->_MotorDriverTurn( TurnOn,  ClockWise); });


//MotorDriverTurn----------------------------------------------

	  
	  
	#define MotorDriverU_MotorDriverTurn_Service \
	inline void MotorDriverTurn(int idOfAO, bool TurnOn, bool ClockWise)\
	{\
		this->RunRequest1(idOfAO,  TurnOn,  ClockWise); \
	}\
	\
	inline Token* MotorDriverTurn_WithWait(int idOfAO, bool TurnOn, bool ClockWise)\
	{\
		return this->RunRequestWithWait1(idOfAO,  TurnOn,  ClockWise); \
	}\
	\
	inline Action1_RETURNTYPE_t MotorDriverTurn_WaitForRequestToFinish(Token* token)\
	{\
		return this->WaitForRequestToFinish1(token  ); \
	}\
	\
	inline void MotorDriverTurn_DoneWithRequest(Token* tokenOfRequest)\
	{\
		return this->DoneWithRequest1(tokenOfRequest); \
	}\
	inline Action1_RETURNTYPE_t MotorDriverTurn_WaitHereForFinish(int idOfAO, bool TurnOn, bool ClockWise)\
	{\
		auto token = this->RunRequestWithWait1(idOfAO,  TurnOn,  ClockWise);\
		Action1_RETURNTYPE_t ret = this->WaitForRequestToFinish1(token);\
		this->DoneWithRequest1(token);\
		return ret;\
	}
	
	#define MotorDriverU_MotorDriverTurn void _MotorDriverTurn(int idOfAO, bool TurnOn, bool ClockWise)
	#define MotorDriverU_MotorDriverTurn_Update bool _MotorDriverTurnUpdate(ActionRequestObjectArgTDU-2* actReq, bool TurnOn, bool ClockWise)   
//Alldefines ------------------
#define MotorDriverU_CTOR \
MotorDriverU_MotorDriverTurn_CTOR 
#define MotorDriverU_Service \
MotorDriverU_MotorDriverTurn_Service 
