//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################


#define PWMDriverU_StartPWMFromSPBLinked_CTOR ActionReq4.SetServiceFunc([](PWMDriverU* p, AENull placeholder){p->_StartPWMFromSPBLinked( placeholder); });ActionReq4.SetUpdateFunc([](PWMDriverU* p, AENull placeholder) {return p->_StartPWMFromSPBLinkedUpdate(&p->ActionReq4,  placeholder); });ActionReq4.SetCancelCleanUpFunc([](PWMDriverU* p){p->_StartPWMFromSPBLinkedCancelCleanup(); });


//StartPWMFromSPBLinked----------------------------------------------

	  
	  
	#define PWMDriverU_StartPWMFromSPBLinked_Service \
	inline void StartPWMFromSPBLinked(int idOfAO, AENull placeholder)\
	{\
		this->RunRequest4(idOfAO,  placeholder); \
	}\
	\
	inline Token* StartPWMFromSPBLinked_WithWait(int idOfAO, AENull placeholder)\
	{\
		return this->RunRequestWithWait4(idOfAO,  placeholder); \
	}\
	\
	inline Action4_RETURNTYPE_t StartPWMFromSPBLinked_WaitForRequestToFinish(Token* token)\
	{\
		return this->WaitForRequestToFinish4(token  ); \
	}\
	\
	inline void StartPWMFromSPBLinked_DoneWithRequest(Token* tokenOfRequest)\
	{\
		return this->DoneWithRequest4(tokenOfRequest); \
	}\
	inline Action4_RETURNTYPE_t StartPWMFromSPBLinked_WaitHereForFinish(int idOfAO, AENull placeholder)\
	{\
		auto token = this->RunRequestWithWait4(idOfAO,  placeholder);\
		Action4_RETURNTYPE_t ret = this->WaitForRequestToFinish4(token);\
		this->DoneWithRequest4(token);\
		return ret;\
	}
	
	#define PWMDriverU_StartPWMFromSPBLinked void _StartPWMFromSPBLinked(int idOfAO, AENull placeholder)
	#define PWMDriverU_StartPWMFromSPBLinked_Update bool _StartPWMFromSPBLinkedUpdate(ActionRequestObjectArgTDU1* actReq, AENull placeholder)   
//Alldefines ------------------
#define PWMDriverU_CTOR \
PWMDriverU_StartPWMFromSPBLinked_CTOR 
#define PWMDriverU_Service \
PWMDriverU_StartPWMFromSPBLinked_Service 
