//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################


#define UARTDriverU_TransmitMsg_CTOR ActionReq1.SetServiceFunc([](UARTDriverU* p, const char* msg, uint32_t lengthOfMsg){p->_TransmitMsg( msg,  lengthOfMsg); });


//TransmitMsg----------------------------------------------

	  
	  
	#define UARTDriverU_TransmitMsg_Service \
	inline void TransmitMsg(int idOfAO, const char* msg, uint32_t lengthOfMsg)\
	{\
		this->RunRequest1(idOfAO,  msg,  lengthOfMsg); \
	}\
	\
	inline Token* TransmitMsg_WithWait(int idOfAO, const char* msg, uint32_t lengthOfMsg)\
	{\
		return this->RunRequestWithWait1(idOfAO,  msg,  lengthOfMsg); \
	}\
	\
	inline Action1_RETURNTYPE_t TransmitMsg_WaitForRequestToFinish(Token* token)\
	{\
		return this->WaitForRequestToFinish1(token  ); \
	}\
	\
	inline void TransmitMsg_DoneWithRequest(Token* tokenOfRequest)\
	{\
		return this->DoneWithRequest1(tokenOfRequest); \
	}\
	inline Action1_RETURNTYPE_t TransmitMsg_WaitHereForFinish(int idOfAO, const char* msg, uint32_t lengthOfMsg)\
	{\
		auto token = this->RunRequestWithWait1(idOfAO,  msg,  lengthOfMsg);\
		Action1_RETURNTYPE_t ret = this->WaitForRequestToFinish1(token);\
		this->DoneWithRequest1(token);\
		return ret;\
	}
	
	#define UARTDriverU_TransmitMsg void _TransmitMsg(int idOfAO, const char* msg, uint32_t lengthOfMsg)
	#define UARTDriverU_TransmitMsg_Update bool _TransmitMsgUpdate(ActionRequestObjectArgTDU-2* actReq, const char* msg, uint32_t lengthOfMsg)   
//Alldefines ------------------
#define UARTDriverU_CTOR \
UARTDriverU_TransmitMsg_CTOR 
#define UARTDriverU_Service \
UARTDriverU_TransmitMsg_Service 
