//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################


#define UploadDataToPcU_UploadDataToPC_CTOR ActionReq4.SetServiceFunc([](UploadDataToPcU* p, char* DataToSend, uint16_t SizeOfData){p->_UploadDataToPC( DataToSend,  SizeOfData); });ActionReq4.SetUpdateFunc([](UploadDataToPcU* p, char* DataToSend, uint16_t SizeOfData) {return p->_UploadDataToPCUpdate(&p->ActionReq4,  DataToSend,  SizeOfData); });ActionReq4.SetCancelCleanUpFunc([](UploadDataToPcU* p){p->_UploadDataToPCCancelCleanup(); });


//UploadDataToPC----------------------------------------------

	  
	  
	#define UploadDataToPcU_UploadDataToPC_Service \
	inline void UploadDataToPC(int idOfAO, char* DataToSend, uint16_t SizeOfData)\
	{\
		this->RunRequest4(idOfAO,  DataToSend,  SizeOfData); \
	}\
	\
	inline Token* UploadDataToPC_WithWait(int idOfAO, char* DataToSend, uint16_t SizeOfData)\
	{\
		return this->RunRequestWithWait4(idOfAO,  DataToSend,  SizeOfData); \
	}\
	\
	inline Action4_RETURNTYPE_t UploadDataToPC_WaitForRequestToFinish(Token* token)\
	{\
		return this->WaitForRequestToFinish4(token  ); \
	}\
	\
	inline void UploadDataToPC_DoneWithRequest(Token* tokenOfRequest)\
	{\
		return this->DoneWithRequest4(tokenOfRequest); \
	}\
	inline Action4_RETURNTYPE_t UploadDataToPC_WaitHereForFinish(int idOfAO, char* DataToSend, uint16_t SizeOfData)\
	{\
		auto token = this->RunRequestWithWait4(idOfAO,  DataToSend,  SizeOfData);\
		Action4_RETURNTYPE_t ret = this->WaitForRequestToFinish4(token);\
		this->DoneWithRequest4(token);\
		return ret;\
	}
	
	#define UploadDataToPcU_UploadDataToPC void _UploadDataToPC(int idOfAO, char* DataToSend, uint16_t SizeOfData)
	#define UploadDataToPcU_UploadDataToPC_Update bool _UploadDataToPCUpdate(ActionRequestObjectArgTDU1* actReq, char* DataToSend, uint16_t SizeOfData)   
#define UploadDataToPcU_CheckIfThereIsPCConnection_CTOR ActionReq5.SetServiceFunc([](UploadDataToPcU* p, bool placeHolderArg){p->_CheckIfThereIsPCConnection( placeHolderArg); });ActionReq5.SetUpdateFunc([](UploadDataToPcU* p, bool placeHolderArg) {return p->_CheckIfThereIsPCConnectionUpdate(&p->ActionReq5,  placeHolderArg); });ActionReq5.SetCancelCleanUpFunc([](UploadDataToPcU* p){p->_CheckIfThereIsPCConnectionCancelCleanup(); });


//CheckIfThereIsPCConnection----------------------------------------------

	  
	  
	#define UploadDataToPcU_CheckIfThereIsPCConnection_Service \
	inline void CheckIfThereIsPCConnection(int idOfAO, bool placeHolderArg)\
	{\
		this->RunRequest5(idOfAO,  placeHolderArg); \
	}\
	\
	inline Token* CheckIfThereIsPCConnection_WithWait(int idOfAO, bool placeHolderArg)\
	{\
		return this->RunRequestWithWait5(idOfAO,  placeHolderArg); \
	}\
	\
	inline Action5_RETURNTYPE_t CheckIfThereIsPCConnection_WaitForRequestToFinish(Token* token)\
	{\
		return this->WaitForRequestToFinish5(token  ); \
	}\
	\
	inline void CheckIfThereIsPCConnection_DoneWithRequest(Token* tokenOfRequest)\
	{\
		return this->DoneWithRequest5(tokenOfRequest); \
	}\
	inline Action5_RETURNTYPE_t CheckIfThereIsPCConnection_WaitHereForFinish(int idOfAO, bool placeHolderArg)\
	{\
		auto token = this->RunRequestWithWait5(idOfAO,  placeHolderArg);\
		Action5_RETURNTYPE_t ret = this->WaitForRequestToFinish5(token);\
		this->DoneWithRequest5(token);\
		return ret;\
	}
	
	#define UploadDataToPcU_CheckIfThereIsPCConnection void _CheckIfThereIsPCConnection(int idOfAO, bool placeHolderArg)
	#define UploadDataToPcU_CheckIfThereIsPCConnection_Update bool _CheckIfThereIsPCConnectionUpdate(ActionRequestObjectArgTDU2* actReq, bool placeHolderArg)   
//Alldefines ------------------
#define UploadDataToPcU_CTOR \
UploadDataToPcU_UploadDataToPC_CTOR \
UploadDataToPcU_CheckIfThereIsPCConnection_CTOR 
#define UploadDataToPcU_Service \
UploadDataToPcU_UploadDataToPC_Service \
UploadDataToPcU_CheckIfThereIsPCConnection_Service 
