//generated file: C:/AERTOSProjects/mpu6050driver\conf\AEConfig.h
//**********************************************************************
//this is an auto-generated file using the template file located in the directory of C:\CodeGenerator\CodeGenerator\bin\Debug\..\..\FileTemplates\Files
//ONLY WRITE CODE IN THE UserCode_Section BLOCKS
//If you write code anywhere else,  it will be overwritten. modify the actual template file if needing to modify code outside usersection blocks.

//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################

#pragma once 
 
 
#ifdef  BOARD_USED__STM32F411RE
#include "stm32f4xx_hal.h"
#endif //  BOARD_USED__STM32F411RE

//UserCode_Sectiondefines
//UserCode_Sectiondefines_end







//####################################
//AE Settings
//####################################

#define AEconfigTICK_RATE_HZ 1000
#define AEconfigMINIMAL_STACK_SIZE 928
#define AEconfigTIMER_TASK_STACK_DEPTH 1500
#define AEconfigTOTAL_HEAP_SIZE 75000
#define AOPRIORITYLOWEST 5
#define AOPRIORITYMEDIUM 10
#define AOPRIORITYHIGHEST 29
#define NUMOFACTIVEOBJECTS 8
#define HIGHEST_NUM_OF_EVT_INSTANCES 2
#define MAX_OUTPUT_SIZE_OF_SPB_SET_TO_TDU 0
#define NUM_OF_TDUS_THAT_FLOW_FROM_SPBS 0
#define MAXSPB_CHAIN_POOLSIZE 5
#define MAXNUMOFINTERPRETORS 3
#define MAXNUMOFOBSERVERINFLUENCES 2
#define MAXNUMOFOBSERVORS 7
#define MAXNUMOFSENSORS 7
#define MAXNUMBEROF_FILTERS 1
#define MAXNUMBEROF_FILTERS_From_A_Sensor 1
#define MaxNumOfAELoops 3
#define MAXNUMBEROFINPUTSIGNALS_TO_A_SPB 1
#define MAXNUMBEROFOUTPUTSIGNALS_TO_A_SPB 1
#define MAXNUM_OF_SUBSCRIBERS_To_A_SPB 1
#define MAXNUM_OF_AE_SUBSCRIPTIONS_To_SPBs 1
#define MAXNUM_OF_TOTAL_SPB_SUBSCRIPTIONS 1
#define TOTALMAXNUMBEROFOUTPUTSIGNALS_TO_ALL_SPBs 10
#define MAXNUMOFTDUSSETTOTheSameSPB 3
#define configAE_USE_TDUs_AsService 1
#define configAE_USE_U_AsService 1
#define configAE_USE_DDSM_AsService 0
#define DontCheckForHardDeadlinesInSPBsForEverySetInput
#define AEDontCheckForCorrectActionRequestTemplate
#define Target_stm32f4








//####################################
//AO defines
//####################################

#define Event1 DummyEVT
#define Event1Size 1

#define I2CPERIPHERAL1 I2CPeripheral<1, PortB, PIN6, PortB, PIN7, 40000> 
#define I2CPERIPHERAL1_Name I2CPERIPHERAL_inst1

#define ClockType1 AEClock<AEObservorSensor, AEObservorInterpretorBaseDUMMY, 6, 0, 0, 0, 0, 0,0, 0, 0,0, 0, 0,0, 0, 0,0, 0, 0,0, 0, 0> 
#define ClockName1 clockForMpu 


#define SensorName1 sensorForAccelx

#define SensorName2 sensorForAccely

#define SensorName3 sensorForAccelz

#define SensorName4 sensorForgyrox

#define SensorName5 sensorForgyroy

#define SensorName6 sensorForgyroz

#define AnyOtherNeededIncludes1 GainFilter 









//####################################
//AE hal defines
//####################################


