//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################

#pragma once 

#define AEITEST_END_TestsAfterTimer_commonAOs(timeInMilliBeforeEnd) 
#define AEITEST_commonAOs(testName, thingToAssert, AssertionMessage) 
#define AEITEST_commonAOs_MUST_PASS_THIS_MANY(testName, thingToAssert, AssertionMessage, passedOnlyAfterThisManyPasses) 
#define AEITEST_commonAOs_IgnoreFirstTests(testName, thingToAssert, AssertionMessage, ignoreFirstRunsNum) 
#define AEITEST_EndTestsIfFalseAssertion_commonAOs(testName, thingToAssert, AssertionMessage) 
#define AEITEST_END_commonAOs 
#define AEITEST_EXPECT_TEST_TO_RUN_commonAOs(testName) 
 

#if BUILD_TESTS__TRUE
//** <h4>integration test enders: will end the test in various ways</h4>*// 
//** the following will end the test after a certain time in milli has passed*// 
#define AEITEST_END_TestsAfterTimer_mpu6050driver(timeInMilliBeforeEnd) _AEITEST_END_TestsAfterTimer(timeInMilliBeforeEnd)
#define AEITEST_mpu6050driver(testName, thingToAssert, AssertionMessage) _AEITEST(testName, thingToAssert, AssertionMessage,0,1) 
#define AEITEST_mpu6050driver_MUST_PASS_THIS_MANY(testName, thingToAssert, AssertionMessage, passedOnlyAfterThisManyPasses) _AEITEST(testName, thingToAssert, AssertionMessage, 0,passedOnlyAfterThisManyPasses) 
#define AEITEST_mpu6050driver_IgnoreFirstTests(testName, thingToAssert, AssertionMessage, ignoreFirstRunsNum) _AEITEST(testName, thingToAssert, AssertionMessage, ignoreFirstRunsNum,1) 
#define AEITEST_EndTestsIfFalseAssertion_mpu6050driver(testName, thingToAssert, AssertionMessage) _AEITEST_EndTestsIfFalseAssertion(testName, thingToAssert, AssertionMessage) 
#define AEITEST_END_mpu6050driver _AEITEST_END
#define AEITEST_EXPECT_TEST_TO_RUN_mpu6050driver(testName) _AEITEST_EXPECT_TEST_TO_RUN(testName)
 
#else
#define AEITEST_END_TestsAfterTimer_mpu6050driver(timeInMilliBeforeEnd) 
#define AEITEST_mpu6050driver(testName, thingToAssert, AssertionMessage) 
#define AEITEST_mpu6050driver_MUST_PASS_THIS_MANY(testName, thingToAssert, AssertionMessage, passedOnlyAfterThisManyPasses) 
#define AEITEST_mpu6050driver_IgnoreFirstTests(testName, thingToAssert, AssertionMessage, ignoreFirstRunsNum) 
#define AEITEST_EndTestsIfFalseAssertion_mpu6050driver(testName, thingToAssert, AssertionMessage) 
#define AEITEST_END_mpu6050driver 
#define AEITEST_EXPECT_TEST_TO_RUN_mpu6050driver(testName) 
 
#endif