//generated file: C:/AERTOSProjects/commonHalAOs\dataupload1VarTest.cpp
//**********************************************************************
//this is an auto-generated file using the template file located in the directory of C:\CodeGenerator\CodeGenerator\bin\Debug\..\..\FileTemplates\Files
//ONLY WRITE CODE IN THE UserCode_Section BLOCKS
//If you write code anywhere else,  it will be overwritten. modify the actual template file if needing to modify code outside usersection blocks.

//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################


 
#if INTEGRATION_TESTS_FOR_commonHalAOs__dataupload1VarTest
 
#include "IntegTestPipeline.h"


#include "AECore.h"
#include "AE_Init.h" 
#include "AEClock.h" 
#include "AEObjects.h" 

DECLARE_ALL_AO_PTR

static void clocl1_callback(TimerHandle_t xTimerHandle);
static void clocl2_callback(TimerHandle_t xTimerHandle);
static int16_t aESensor1_data[1];




//UserCode_Sectiona
//UserCode_Sectiona_end

void RunSelectedIntegrationTest_dataupload1VarTest()
{

AE_Init();
 //UserCode_Sectionbeforemain
//UserCode_Sectionbeforemain_end












static AEClock<AEObservorSensor, AEObservorInterpretorBaseDUMMY, 0, 0, 0, 0, 0, 0,0, 0, 0,0, 0, 0,1, 0, 0,0, 0, 0,0, 0, 0> clocl1L(1000, clocl1_callback);
clocl1 = &clocl1L;

static AEClock<AEObservorSensorDUMMY, AEObservorInterpretorBaseDUMMY, 0, 0, 1, 0, 0, 0,0, 0, 0,0, 0, 0,0, 0, 0,0, 0, 0,0, 0, 0> clocl2L(1000, clocl2_callback);
clocl2 = &clocl2L;

static UploadDataToPcU uploadDataToPcU_L; uploadDataToPcU_L.Init(AEPriorities::MediumPriority);
uploadDataToPcU = &uploadDataToPcU_L;




static DataToPC1_SPB< false,  100> dataToPC_SPBL; dataToPC_SPBL.InitSPBObserver(StyleOfSPB::EachSPBTask); 
dataToPC_SPB = &dataToPC_SPBL;

static AEObservorSensorFilterOut<> aESensor1L((int16_t*) aESensor1_data, SensorResolution::Resolution16Bit  );
aESensor1 = &aESensor1L;



//UserCode_Sectionbeforelinks
//UserCode_Sectionbeforelinks_end
static float dataToPC_SPBchBuffer1[100];
dataToPC_SPB->AddSignalFlowLinkToChannelWithCopy1(aESensor1, dataToPC_SPBchBuffer1, 0);



//UserCode_Sectionbeforeclock
//UserCode_Sectionbeforeclock_end
clocl1->SetObservorToClock(aESensor1, AEClock_PrescalerEnum::PRESCALER16);
clocl2->SetTDUToClock(uploadDataToPcU, AEClock_PrescalerEnum::PRESCALER1);


//AEITEST_END_TestsAfterTimer_commonHalAOs(5000);
//UserCode_Sectionb
	uploadDataToPcU->UserInitialize(UARTPERIPHERAL_inst2);
	dataToPC_SPB->UserInitialize(uploadDataToPcU);
//UserCode_Sectionb_end

AEAO::ConfigureAndStart();
}


//UserCode_Sectionc
//UserCode_Sectionc_end


static void clocl1_callback(TimerHandle_t xTimerHandle) {  
  //UserCode_Sectionclocl1before
//UserCode_Sectionclocl1before_end 
  
 clocl1->Tick(); 
  //UserCode_Sectionclocl1after
//UserCode_Sectionclocl1after_end 
}static void clocl2_callback(TimerHandle_t xTimerHandle) {  
  //UserCode_Sectionclocl2before
//UserCode_Sectionclocl2before_end 
  
 clocl2->Tick(); 
  //UserCode_Sectionclocl2after
	aESensor1_data[0]++;
//UserCode_Sectionclocl2after_end 
}


#endif