//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################


#define MotorDriverSpeedControllerTDU_MoveToAngularPositionWithSpeed_CTOR ActionReq4.SetServiceFunc([](MotorDriverSpeedControllerTDU* p, int16_t StepCountToTurnTo, float speedToTurnAt, bool withRamping){p->_MoveToAngularPositionWithSpeed( StepCountToTurnTo,  speedToTurnAt,  withRamping); });ActionReq4.SetUpdateFunc([](MotorDriverSpeedControllerTDU* p, int16_t StepCountToTurnTo, float speedToTurnAt, bool withRamping) {return p->_MoveToAngularPositionWithSpeedUpdate(&p->ActionReq4,  StepCountToTurnTo,  speedToTurnAt,  withRamping); });ActionReq4.SetCancelCleanUpFunc([](MotorDriverSpeedControllerTDU* p){p->_MoveToAngularPositionWithSpeedCancelCleanup(); });


//MoveToAngularPositionWithSpeed----------------------------------------------

	  
	  
	#define MotorDriverSpeedControllerTDU_MoveToAngularPositionWithSpeed_Service \
	inline void MoveToAngularPositionWithSpeed(int idOfAO, int16_t StepCountToTurnTo, float speedToTurnAt, bool withRamping)\
	{\
		this->RunRequest4(idOfAO,  StepCountToTurnTo,  speedToTurnAt,  withRamping); \
	}\
	\
	inline Token* MoveToAngularPositionWithSpeed_WithWait(int idOfAO, int16_t StepCountToTurnTo, float speedToTurnAt, bool withRamping)\
	{\
		return this->RunRequestWithWait4(idOfAO,  StepCountToTurnTo,  speedToTurnAt,  withRamping); \
	}\
	\
	inline Action4_RETURNTYPE_t MoveToAngularPositionWithSpeed_WaitForRequestToFinish(Token* token)\
	{\
		return this->WaitForRequestToFinish4(token  ); \
	}\
	\
	inline void MoveToAngularPositionWithSpeed_DoneWithRequest(Token* tokenOfRequest)\
	{\
		return this->DoneWithRequest4(tokenOfRequest); \
	}\
	inline Action4_RETURNTYPE_t MoveToAngularPositionWithSpeed_WaitHereForFinish(int idOfAO, int16_t StepCountToTurnTo, float speedToTurnAt, bool withRamping)\
	{\
		auto token = this->RunRequestWithWait4(idOfAO,  StepCountToTurnTo,  speedToTurnAt,  withRamping);\
		Action4_RETURNTYPE_t ret = this->WaitForRequestToFinish4(token);\
		this->DoneWithRequest4(token);\
		return ret;\
	}
	
	#define MotorDriverSpeedControllerTDU_MoveToAngularPositionWithSpeed void _MoveToAngularPositionWithSpeed(int idOfAO, int16_t StepCountToTurnTo, float speedToTurnAt, bool withRamping)
	#define MotorDriverSpeedControllerTDU_MoveToAngularPositionWithSpeed_Update bool _MoveToAngularPositionWithSpeedUpdate(ActionRequestObjectArgTDU1* actReq, int16_t StepCountToTurnTo, float speedToTurnAt, bool withRamping)   
#define MotorDriverSpeedControllerTDU_MoveAtSpeed_CTOR ActionReq5.SetServiceFunc([](MotorDriverSpeedControllerTDU* p, float speedToTurnAt, bool withRamping){p->_MoveAtSpeed( speedToTurnAt,  withRamping); });ActionReq5.SetUpdateFunc([](MotorDriverSpeedControllerTDU* p, float speedToTurnAt, bool withRamping) {return p->_MoveAtSpeedUpdate(&p->ActionReq5,  speedToTurnAt,  withRamping); });ActionReq5.SetCancelCleanUpFunc([](MotorDriverSpeedControllerTDU* p){p->_MoveAtSpeedCancelCleanup(); });


//MoveAtSpeed----------------------------------------------

	  
	  
	#define MotorDriverSpeedControllerTDU_MoveAtSpeed_Service \
	inline void MoveAtSpeed(int idOfAO, float speedToTurnAt, bool withRamping)\
	{\
		this->RunRequest5(idOfAO,  speedToTurnAt,  withRamping); \
	}\
	\
	inline Token* MoveAtSpeed_WithWait(int idOfAO, float speedToTurnAt, bool withRamping)\
	{\
		return this->RunRequestWithWait5(idOfAO,  speedToTurnAt,  withRamping); \
	}\
	\
	inline Action5_RETURNTYPE_t MoveAtSpeed_WaitForRequestToFinish(Token* token)\
	{\
		return this->WaitForRequestToFinish5(token  ); \
	}\
	\
	inline void MoveAtSpeed_DoneWithRequest(Token* tokenOfRequest)\
	{\
		return this->DoneWithRequest5(tokenOfRequest); \
	}\
	inline Action5_RETURNTYPE_t MoveAtSpeed_WaitHereForFinish(int idOfAO, float speedToTurnAt, bool withRamping)\
	{\
		auto token = this->RunRequestWithWait5(idOfAO,  speedToTurnAt,  withRamping);\
		Action5_RETURNTYPE_t ret = this->WaitForRequestToFinish5(token);\
		this->DoneWithRequest5(token);\
		return ret;\
	}
	
	#define MotorDriverSpeedControllerTDU_MoveAtSpeed void _MoveAtSpeed(int idOfAO, float speedToTurnAt, bool withRamping)
	#define MotorDriverSpeedControllerTDU_MoveAtSpeed_Update bool _MoveAtSpeedUpdate(ActionRequestObjectArgTDU2* actReq, float speedToTurnAt, bool withRamping)   
//Alldefines ------------------
#define MotorDriverSpeedControllerTDU_CTOR \
MotorDriverSpeedControllerTDU_MoveToAngularPositionWithSpeed_CTOR \
MotorDriverSpeedControllerTDU_MoveAtSpeed_CTOR 
#define MotorDriverSpeedControllerTDU_Service \
MotorDriverSpeedControllerTDU_MoveToAngularPositionWithSpeed_Service \
MotorDriverSpeedControllerTDU_MoveAtSpeed_Service 
