//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################


#define RYLR896_U_SendData_CTOR ActionReq4.SetServiceFunc([](RYLR896_U* p, int16_t addressOfLoraModToSendTo, char* dataToSend, int8_t payloadSize){p->_SendData( addressOfLoraModToSendTo,  dataToSend,  payloadSize); });ActionReq4.SetUpdateFunc([](RYLR896_U* p, int16_t addressOfLoraModToSendTo, char* dataToSend, int8_t payloadSize) {return p->_SendDataUpdate(&p->ActionReq4,  addressOfLoraModToSendTo,  dataToSend,  payloadSize); });ActionReq4.SetCancelCleanUpFunc([](RYLR896_U* p){p->_SendDataCancelCleanup(); });


//SendData----------------------------------------------

	  
	  
	#define RYLR896_U_SendData_Service \
	inline void SendData(int idOfAO, int16_t addressOfLoraModToSendTo, char* dataToSend, int8_t payloadSize)\
	{\
		this->RunRequest4(idOfAO,  addressOfLoraModToSendTo,  dataToSend,  payloadSize); \
	}\
	\
	inline Token* SendData_WithWait(int idOfAO, int16_t addressOfLoraModToSendTo, char* dataToSend, int8_t payloadSize)\
	{\
		return this->RunRequestWithWait4(idOfAO,  addressOfLoraModToSendTo,  dataToSend,  payloadSize); \
	}\
	\
	inline Action4_RETURNTYPE_t SendData_WaitForRequestToFinish(Token* token)\
	{\
		return this->WaitForRequestToFinish4(token  ); \
	}\
	\
	inline void SendData_DoneWithRequest(Token* tokenOfRequest)\
	{\
		return this->DoneWithRequest4(tokenOfRequest); \
	}\
	inline Action4_RETURNTYPE_t SendData_WaitHereForFinish(int idOfAO, int16_t addressOfLoraModToSendTo, char* dataToSend, int8_t payloadSize)\
	{\
		auto token = this->RunRequestWithWait4(idOfAO,  addressOfLoraModToSendTo,  dataToSend,  payloadSize);\
		Action4_RETURNTYPE_t ret = this->WaitForRequestToFinish4(token);\
		this->DoneWithRequest4(token);\
		return ret;\
	}
	
	#define RYLR896_U_SendData void _SendData(int idOfAO, int16_t addressOfLoraModToSendTo, char* dataToSend, int8_t payloadSize)
	#define RYLR896_U_SendData_Update bool _SendDataUpdate(ActionRequestObjectArgTDU1* actReq, int16_t addressOfLoraModToSendTo, char* dataToSend, int8_t payloadSize)   
//Alldefines ------------------
#define RYLR896_U_CTOR \
RYLR896_U_SendData_CTOR 
#define RYLR896_U_Service \
RYLR896_U_SendData_Service 
