//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################

#pragma once 

#define AEITEST_END_TestsAfterTimer_commonAOs(timeInMilliBeforeEnd) 
#define AEITEST_commonAOs(testName, thingToAssert, AssertionMessage) 
#define AEITEST_commonAOs_MUST_PASS_THIS_MANY(testName, thingToAssert, AssertionMessage, passedOnlyAfterThisManyPasses) 
#define AEITEST_commonAOs_IgnoreFirstTests(testName, thingToAssert, AssertionMessage, ignoreFirstRunsNum) 
#define AEITEST_EndTestsIfFalseAssertion_commonAOs(testName, thingToAssert, AssertionMessage) 
#define AEITEST_END_commonAOs 
#define AEITEST_EXPECT_TEST_TO_RUN_commonAOs(testName) 
#define AEITEST_END_TestsAfterTimer_commonHalAOs(timeInMilliBeforeEnd) 
#define AEITEST_commonHalAOs(testName, thingToAssert, AssertionMessage) 
#define AEITEST_commonHalAOs_MUST_PASS_THIS_MANY(testName, thingToAssert, AssertionMessage, passedOnlyAfterThisManyPasses) 
#define AEITEST_commonHalAOs_IgnoreFirstTests(testName, thingToAssert, AssertionMessage, ignoreFirstRunsNum) 
#define AEITEST_EndTestsIfFalseAssertion_commonHalAOs(testName, thingToAssert, AssertionMessage) 
#define AEITEST_END_commonHalAOs 
#define AEITEST_EXPECT_TEST_TO_RUN_commonHalAOs(testName) 
 

#if BUILD_TESTS__TRUE
//** <h4>integration test enders: will end the test in various ways</h4>*// 
//** the following will end the test after a certain time in milli has passed*// 
#define AEITEST_END_TestsAfterTimer_MotorDriverEncoder(timeInMilliBeforeEnd) _AEITEST_END_TestsAfterTimer(timeInMilliBeforeEnd)
#define AEITEST_MotorDriverEncoder(testName, thingToAssert, AssertionMessage) _AEITEST(testName, thingToAssert, AssertionMessage,0,1) 
#define AEITEST_MotorDriverEncoder_MUST_PASS_THIS_MANY(testName, thingToAssert, AssertionMessage, passedOnlyAfterThisManyPasses) _AEITEST(testName, thingToAssert, AssertionMessage, 0,passedOnlyAfterThisManyPasses) 
#define AEITEST_MotorDriverEncoder_IgnoreFirstTests(testName, thingToAssert, AssertionMessage, ignoreFirstRunsNum) _AEITEST(testName, thingToAssert, AssertionMessage, ignoreFirstRunsNum,1) 
#define AEITEST_EndTestsIfFalseAssertion_MotorDriverEncoder(testName, thingToAssert, AssertionMessage) _AEITEST_EndTestsIfFalseAssertion(testName, thingToAssert, AssertionMessage) 
#define AEITEST_END_MotorDriverEncoder _AEITEST_END
#define AEITEST_EXPECT_TEST_TO_RUN_MotorDriverEncoder(testName) _AEITEST_EXPECT_TEST_TO_RUN(testName)
 
#else
#define AEITEST_END_TestsAfterTimer_MotorDriverEncoder(timeInMilliBeforeEnd) 
#define AEITEST_MotorDriverEncoder(testName, thingToAssert, AssertionMessage) 
#define AEITEST_MotorDriverEncoder_MUST_PASS_THIS_MANY(testName, thingToAssert, AssertionMessage, passedOnlyAfterThisManyPasses) 
#define AEITEST_MotorDriverEncoder_IgnoreFirstTests(testName, thingToAssert, AssertionMessage, ignoreFirstRunsNum) 
#define AEITEST_EndTestsIfFalseAssertion_MotorDriverEncoder(testName, thingToAssert, AssertionMessage) 
#define AEITEST_END_MotorDriverEncoder 
#define AEITEST_EXPECT_TEST_TO_RUN_MotorDriverEncoder(testName) 
 
#endif