//generated file: C:/AERTOSProjects/commonAOs\conf\AEConfig.h
//**********************************************************************
//this is an auto-generated file using the template file located in the directory of C:\CodeGenerator\CodeGenerator\bin\Debug\..\..\FileTemplates\Files
//ONLY WRITE CODE IN THE UserCode_Section BLOCKS
//If you write code anywhere else,  it will be overwritten. modify the actual template file if needing to modify code outside usersection blocks.

//############################################### 
//this is an autogenerated file using cgen's macro2 command. Dont modify this file here unless it is in user sections 
//###############################################

#pragma once 
 
 
#ifdef  BOARD_USED__STM32F411RE
#include "stm32f4xx_hal.h"
#endif //  BOARD_USED__STM32F411RE

//UserCode_Sectiondefines
//UserCode_Sectiondefines_end







//####################################
//AE Settings
//####################################

#define AEconfigTICK_RATE_HZ 1000
#define AEconfigMINIMAL_STACK_SIZE 928
#define AEconfigTIMER_TASK_STACK_DEPTH 1500
#define AEconfigTOTAL_HEAP_SIZE 75000
#define AOPRIORITYLOWEST 5
#define AOPRIORITYMEDIUM 10
#define AOPRIORITYHIGHEST 29
#define NUMOFACTIVEOBJECTS 7
#define HIGHEST_NUM_OF_EVT_INSTANCES 2
#define MAX_OUTPUT_SIZE_OF_SPB_SET_TO_TDU 0
#define NUM_OF_TDUS_THAT_FLOW_FROM_SPBS 0
#define MAXSPB_CHAIN_POOLSIZE 5
#define MAXNUMOFINTERPRETORS 3
#define MAXNUMOFOBSERVERINFLUENCES 2
#define MAXNUMOFOBSERVORS 7
#define MAXNUMOFSENSORS 2
#define MAXNUMBEROF_FILTERS 2
#define MAXNUMBEROF_FILTERS_From_A_Sensor 2
#define MaxNumOfAELoops 3
#define MAXNUMBEROFINPUTSIGNALS_TO_A_SPB 3
#define MAXNUMBEROFOUTPUTSIGNALS_TO_A_SPB 10
#define MAXNUM_OF_SUBSCRIBERS_To_A_SPB 1
#define MAXNUM_OF_AE_SUBSCRIPTIONS_To_SPBs 1
#define MAXNUM_OF_TOTAL_SPB_SUBSCRIPTIONS 1
#define TOTALMAXNUMBEROFOUTPUTSIGNALS_TO_ALL_SPBs 10
#define MAXNUMOFTDUSSETTOTheSameSPB 3
#define configAE_USE_TDUs_AsService 1
#define configAE_USE_U_AsService 1
#define configAE_USE_DDSM_AsService 0
#define DontCheckForHardDeadlinesInSPBsForEverySetInput
#define AEDontCheckForCorrectActionRequestTemplate
#define Target_stm32f4








//####################################
//AO defines
//####################################

#define Event1 DummyEVT
#define Event1Size 1

#define AnyOtherNeededIncludes1 AddOrSubFilter 

#define ClockType1 AEClock<AEObservorSensor, AEObservorInterpretorBaseDUMMY, 1, 0, 0, 0, 0, 0,0, 0, 0,0, 0, 0,0, 0, 0,0, 0, 0,0, 0, 0> 
#define ClockName1 clock1 

#define SensorName1 sensor1

#define AnyOtherNeededIncludes2 AngularDerivativeDiscreteFilter 

#define AnyOtherNeededIncludes3 MovingAverageFilter 

#define AnyOtherNeededIncludes4 DerivativeFilter 

#define AnyOtherNeededIncludes5 HighOrLowFilter 

#define AOInclude1 IfRightOnSPB
#define TemplateToAO1 template<bool isSubscribable, TEMPLATESPB_Filters>
#define ClassNameOfAO1 IfRightOnSPB
#define TypeOfAO1_1 IfRightOnSPB< false>
#define InstanceNameOfAO1_1 ifRightOnSPB

#define AOInclude2 AverageSPB
#define TemplateToAO2 template<bool isSubscribable, uint32_t CHANNELCOUNTBUFFER1, TEMPLATESPB_Filters>
#define ClassNameOfAO2 AverageSPB
#define TypeOfAO2_1 AverageSPB< false,  10>
#define InstanceNameOfAO2_1 averageSPB

#define AOInclude3 PID_SPB
#define TemplateToAO3 template<bool isSubscribable, uint32_t CHANNEL_CONSUMPTION_SIZE1, TEMPLATESPB_Filters>
#define ClassNameOfAO3 PID_SPB
#define TypeOfAO3_1 PID_SPB< false,  1>
#define InstanceNameOfAO3_1 pidSPB

#define AOInclude4 ThreeDimensionalVectorSPB
#define TemplateToAO4 template<bool isSubscribable, TEMPLATESPB_Filters>
#define ClassNameOfAO4 ThreeDimensionalVectorSPB
#define TypeOfAO4_1 ThreeDimensionalVectorSPB< false>
#define InstanceNameOfAO4_1 threeDimensionalVectorSPB

#define AOInclude5 IfAllTrueSPB
#define TemplateToAO5 template< uint16_t NUMOFINPUTSIGNALS, bool isSubscribable, uint32_t CHANNELCOUNTBUFFER, TEMPLATESPB_Filters>
#define ClassNameOfAO5 IfAllTrueSPB
#define TypeOfAO5_1 IfAllTrueSPB< 3,  false, 1>
#define InstanceNameOfAO5_1 ifAllTrueSPB




//####################################
//AE hal defines
//####################################


